redmine_db_host: "rc1a-87if083nhpqv7rr9.mdb.yandexcloud.net"
redmine_db_port: 6432

redmine_db_password: "{{ vault_redmine_db_password }}"
redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"

datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: datadoghq.com
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Redmine HTTP check
        method: GET
        timeout: 5
        url: "http://{{ ansible_host }}:{{ redmine_port }}"
